version: '3.8'

services:
  postgres_delivery:
    image: postgres
    container_name: postgres_delivery
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: T~wU3Q/V=703'6@
      POSTGRES_DB: fiap
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: