spring.application.name=notificacao-app

#Configuration PostgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5435/fiap
spring.datasource.username=admin
spring.datasource.password=T~wU3Q/V=703'6@

spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always

#Configuration RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=T~wU3Q/V=703'6@

spring.cloud.stream.bindings.supplier-out-0.destination=notification.v1
spring.cloud.stream.bindings.notificacaoQueueGateway-in-0.destination=notification.v1-created
spring.cloud.stream.bindings.pedidoQueueGateway-in-0.group=notification